version: "3.1"
services:
    mariadb:
      image: mariadb:10.4
      container_name: elclaustro-mariadb
      restart: unless-stopped
      working_dir: /application
      volumes:
        - ./mariadb/databases:/var/lib/mysql
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=rootpasswd
        - MYSQL_DATABASE=
        - MYSQL_USER=
        - MYSQL_PASSWORD=
#      ports:
#        - "3306:3306"

    webserver:
      image: nginx:mainline-alpine
      container_name: elclaustro-nginx
      restart: unless-stopped
      working_dir: /application
      environment:
       - PUID=1001
       - PGID=1001
       - UMASK_SET=022

      volumes:
          - .:/application
          # CERTS
          - ./path/to/cert.crt:/etc/nginx/certs/cert.crt
          - ./path/to/key.key:/etc/nginx/certs/key.key
          # CONFS NGINX 
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
 
      ports:
#       - "80:80"
       - "443:443"

    php-fpm:
      build: phpdocker/php-fpm
#      image: ngeorger/php74fpm:latest
      container_name: elclaustro-php-fpm
      restart: unless-stopped
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
#      ports:
#        - "9000:9000"
